---
title: "cis_section_1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# source-------------------------
source('~/Box Sync/cptac2p_analysis/phospho_network/phospho_network_shared.R')
reg_nonNA <- 20
enzyme_type <- "kinase"
ppnD <- "~/Box Sync/cptac2p/analysis_results/phospho_network/"
```

``` {r}
# inputs ------------------------------------------------------------------
ptms_site_pairs_sup <- read_csv(paste0(ppnD, "compile_enzyme_substrate/tables/compile_omnipath_networkin_depod_signor_manual/Omnipath_NetworKin_DEPOD_SignorNotSiteMapped_manualAdded.csv"))
ptms_site_pairs_sup <- ptms_site_pairs_sup[ptms_site_pairs_sup$Source != "NetKIN" | ptms_site_pairs_sup$Source == "NetKIN" & ptms_site_pairs_sup$networkin_score >=5,]
ptms_site_pairs_sup <- data.frame(ptms_site_pairs_sup)
ptms_site_pairs_sup$pair <- paste0(ptms_site_pairs_sup$pair_pro, ":", ptms_site_pairs_sup$SUB_MOD_RSD)
ptms_site_pairs_sup$SELF <- ifelse(as.vector(ptms_site_pairs_sup$GENE) == as.vector(ptms_site_pairs_sup$SUB_GENE), "cis", "trans")
ptms_site_pairs_sup$rsd <- paste0(ptms_site_pairs_sup$SUB_GENE, "_", ptms_site_pairs_sup$SUB_MOD_RSD)
k_s_table <- ptms_site_pairs_sup[ptms_site_pairs_sup$enzyme_type == enzyme_type,]

## load PSP k-s table to get autophosphorylated pairs
#     k_s_psp <- load_ks_table(protein = enzyme_type)
k_s_psp$SELF <- ifelse(as.vector(k_s_psp$GENE) == as.vector(k_s_psp$SUB_GENE), "cis", "trans")
```

``` {r load-regression-result}
## load regression table

regression <- fread(input = paste0(ppnD, "regression/tables/", "change_regression_nonNA/", 
                                   enzyme_type, "_substrate_regression_cptac2p_3can_tumor",
                                   "_reg_nonNA", reg_nonNA, ".txt"), data.table = F)
regression <- markSigSiteCan(regression = regression, sig_thres = 0.05, enzyme_type = enzyme_type)
regression$rsd <- paste0(regression$SUB_GENE, "_", regression$SUB_MOD_RSD)
regression$rsd[regression$SELF == "cis" & regression$fdr_sig & regression$coef_sig] %>% head
regression$regulated <- (regression$fdr_sig & regression$coef_sig)

cis_detected_sites <- unique(regression$rsd[regression$SELF == "cis"])
cis_detected_sites %>% length()

cis_regulated_sites <- unique(regression$rsd[regression$SELF == "cis" & regression$fdr_sig & regression$coef_sig])
cis_regulated_sites %>% length()

trans_detected_sites <- unique(regression$rsd[regression$SELF == "trans"])
trans_detected_sites %>% length()

trans_regulated_sites <- unique(regression$rsd[regression$SELF == "trans" & regression$fdr_sig & regression$coef_sig])
trans_regulated_sites %>% length()
```

## autophosphorylation

```{r known_autophosphorylating_kinases}

kinase_cis <- unique(c(as.vector(k_s_table$GENE[as.vector(k_s_table$GENE) == as.vector(k_s_table$SUB_GENE)]), 
                    as.vector(k_s_psp$GENE[as.vector(k_s_psp$GENE)==as.vector(k_s_psp$SUB_GENE)])))

kinase_cis %>% length()
```

```{r known_autophosphorylating_sites}
k_s_psp$rsd <- paste0(k_s_psp$SUB_GENE, "_", k_s_psp$SUB_MOD_RSD)
knownauto_rsd_list <- unique(k_s_psp$rsd[k_s_psp$SELF == "cis"])
knownauto_rsd_list %>% length()
```

## get activation loop reported to be autophosphorylated
```{r reformat_AL_table}
# ## Load UniProt annotation
# uniprot_tbl <- read_tsv(
#     '../../../../Ding_Lab/Projects_Current/Multiple_Myeloma/MMY_Proteomics/Resources/all_uniprot_canonical_isoform_mappings.uniprotkb_201801.tsv.gz',
#     col_types = cols(
#         uniprot_entry = col_character(),
#         uniprot_name = col_character(),
#         uniprot_isoform = col_character(),
#         hugogene_id = col_integer(),
#         symbol = col_character()
#     )
# )
# uniprot_tbl %>% head()
# uniprot_tbl <- data.frame(uniprot_tbl)
# uniprot_tbl$uniprot_prefix <- str_split_fixed(string = uniprot_tbl$uniprot_name, pattern = "\\_", 2)[,1]
# uniprot_tbl %>% head()
# ## change the protein names in the above table with gene symbol
# AL_tab$symbol <- sapply(X = as.vector(AL_tab$Kinase), FUN = function(k, uniprot_tbl) {
#   unique(uniprot_tbl$symbol[uniprot_tbl$uniprot_prefix == k])}, uniprot_tbl = uniprot_tbl)
# AL_tab %>% head()

## load AL phosphosite table
AL_tab <- read_excel("~/Box Sync/cptac2p/resources/autophosphorylation/AL_autophosphorylation.xlsx")

## get the known autophosphorylated AL sites
AL_tab_wsite <- AL_tab[AL_tab$` Putative activation loop phosphorylation site(s)` != "?",]
AL_tab_wsite %>% head()

AL_rsd_list <- sapply(1:nrow(AL_tab_wsite), function(i, AL_tab_wsite) {
  kinase <- as.character(AL_tab_wsite$Kinase[i])
  rsds <- unlist(strsplit(x = AL_tab_wsite$` Putative activation loop phosphorylation site(s)`[i], split = "\\, "))
  k_rsds <- paste0(kinase, "_", rsds)
  return(k_rsds)
}, AL_tab_wsite = AL_tab_wsite)
AL_rsd_list <- unlist(AL_rsd_list)
unlist(AL_rsd_list) %>% head()
unlist(AL_rsd_list) %>% length()

## get the known autophosphorylated-only AL sites
AL_tab_wsite_autoonly <- AL_tab[AL_tab$` Putative activation loop phosphorylation site(s)` != "?" & AL_tab$`Activation loop phosphorylation showed to be required for activity` == "+" & AL_tab$`Is the site known to be phosphorylated by other kinases?` == "No",]
AL_tab_wsite_autoonly %>% head()
AL_tab_wsite_autoonly %>% nrow()

AL_autoonly_rsd_list <- sapply(1:nrow(AL_tab_wsite_autoonly), function(i, AL_tab_wsite_autoonly) {
  kinase <- as.character(AL_tab_wsite_autoonly$Kinase[i])
  rsds <- unlist(strsplit(x = AL_tab_wsite_autoonly$` Putative activation loop phosphorylation site(s)`[i], split = "\\, "))
  k_rsds <- paste0(kinase, "_", rsds)
  return(k_rsds)
}, AL_tab_wsite_autoonly = AL_tab_wsite_autoonly)
AL_autoonly_rsd_list <- unlist(AL_autoonly_rsd_list)
AL_autoonly_rsd_list %>% length()
```
``` {r cis-regulated-auto-sites}
intersect(cis_detected_sites, knownauto_rsd_list) %>% length()
intersect(cis_regulated_sites, knownauto_rsd_list) %>% length()
```

``` {r cis-regulated-AL-sites}
intersect(cis_detected_sites, unlist(AL_rsd_list))
intersect(cis_detected_sites, unlist(AL_rsd_list)) %>% length()

intersect(cis_regulated_sites, unlist(AL_rsd_list))
intersect(cis_regulated_sites, unlist(AL_rsd_list)) %>% length()

regression[regression$rsd %in% intersect(cis_regulated_sites, unlist(AL_rsd_list)) & regression$SELF == "cis",] %>%
  select(pair, regulated, Cancer)
```

``` {r not-cis-regulated-auto-sites}
setdiff(intersect(cis_detected_sites, knownauto_rsd_list), cis_regulated_sites)

intersect(setdiff(intersect(cis_detected_sites, knownauto_rsd_list), cis_regulated_sites), trans_detected_sites) %>% length()
intersect(setdiff(intersect(cis_detected_sites, knownauto_rsd_list), cis_regulated_sites), trans_regulated_sites)
AL_rsd_notcis_trans_list <- intersect(intersect(setdiff(intersect(cis_detected_sites, knownauto_rsd_list), cis_regulated_sites), trans_regulated_sites), unlist(AL_rsd_list))
AL_rsd_notcis_trans_list
regression[regression$rsd %in% AL_rsd_notcis_trans_list & regression$regulated,] %>%
  select(pair, regulated, Cancer)

```

``` {r auto-only-AL-sites}
AK_autoonly_gene_list <- unique(str_split_fixed(string = AL_autoonly_rsd_list, pattern = "_", n = 2)[,1])
str_split_fixed(string = AL_autoonly_rsd_list, pattern = "_", n = 2)[,1] %>% unique %>% length()
setdiff(unique(str_split_fixed(string = AL_autoonly_rsd_list, pattern = "_", n = 2)[,1]), k_s_table$SUB_GENE[k_s_table$SELF == "trans"])
setdiff(unlist(str_split_fixed(string = AL_autoonly_rsd_list, pattern = "_", n = 2)[,1]), union(k_s_psp$SUB_GENE[k_s_psp$SELF == "trans"], k_s_table$SUB_GENE[k_s_table$SELF == "trans"]))

intersect(AK_autoonly_gene_list, unique(k_s_table$SUB_GENE[k_s_table$SELF == "trans"])) %>% length()
intersect(AK_autoonly_gene_list, unique(regression$SUB_GENE[regression$SELF == "trans"])) %>% length()
intersect(trans_detected_sites, AL_autoonly_rsd_list) %>% length()
intersect(trans_regulated_sites, AL_autoonly_rsd_list)

intersect(AL_autoonly_rsd_list, k_s_table$rsd[k_s_table$SELF == "trans"])
intersect(AL_autoonly_rsd_list, k_s_psp$rsd[k_s_psp$SELF == "trans"])
regression[regression$rsd %in% intersect(trans_regulated_sites, AL_autoonly_rsd_list) & regression$regulated,]

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
