---
title: "Trans regulation specificity"
output: html_document
---
## source

```{r setup, include=FALSE}
baseD = "/Users/yigewu/Box\ Sync/"
library(knitr)
opts_knit$set(root.dir = baseD)
setwd(baseD)
source('./cptac2p_analysis/preprocess_files/preprocess_files_shared.R')
source("./cptac2p_analysis/phospho_network/phospho_network_shared.R")
```

## set variables
``` {r variables}
cancers2process <- c("BRCA", "OV", "CO", "UCEC", "CCRCC")
```



## inputs
``` {r input-ks-table}
omnipath_tab <- load_omnipath()
omnipath_tab <- annotate_enzyme_type(regression = omnipath_tab, kinases = kinases, phosphatases = phosphatases)
omnipath_tab %>%
  filter(enzyme_type != "") %>%
  filter(!(Source %in% c("NetKIN", "PhosphoNetworks", "MIMP"))) %>%
  select(pair_pro) %>%
  unique() %>%
  nrow()

omnipath_tab %>%
  filter(enzyme_type == "kinase") %>%
  filter(!(Source %in% c("NetKIN", "PhosphoNetworks", "MIMP"))) %>%
  select(pair_pro) %>%
  unique() %>%
  nrow()

omnipath_tab %>%
  filter(enzyme_type == "kinase") %>%
  filter(!(Source %in% c("NetKIN", "PhosphoNetworks", "MIMP"))) %>%
  filter(as.vector(GENE) != as.vector(SUB_GENE)) %>%
  select(pair_pro) %>%
  unique() %>%
  nrow()

omnipath_tab %>%
  filter(enzyme_type == "phosphatase") %>%
  filter(!(Source %in% c("NetKIN", "PhosphoNetworks", "MIMP"))) %>%
  select(pair_pro) %>%
  unique() %>%
  nrow()


c(psp_tab %>%
  filter(as.vector(GENE) == as.vector(SUB_GENE)) %>%
  filter(!(pair_pro %in% omnipath_tab$pair_pro)) %>%
  select(pair_pro) %>%
  unique() %>%
  unlist() %>%
  as.vector(),
  omnipath_tab %>%
  filter(enzyme_type == "kinase") %>%
  filter(!(Source %in% c("NetKIN", "PhosphoNetworks", "MIMP"))) %>%
  filter(as.vector(GENE) == as.vector(SUB_GENE)) %>%
  select(pair_pro) %>%
  unique() %>%
  unlist() %>%
  as.vector()) %>%
  unique() %>%
  length()

39+6119
```

```{r input-regression-and-clean-up}
regression <- fread(input = paste0(ppnD, "regression/tables/annotate_regression_with_mut_impact/", 
                                   "regression_cptac2p_cptac3_tumor_reg_nonNA20_mut_impact_cancer_specificity_annotated.txt"),
                    data.table = F)
reg_sig <- c(0.05, 0.05); names(reg_sig) <- c("kinase", "phosphatase")
regression %>% nrow()
regression <- regression %>%
  filter(regression$pair_pro %in% omnipath_tab$pair_pro[!(omnipath_tab$Source %in% c("NetKIN", "PhosphoNetworks", "MIMP"))])
regression %>% nrow()

# regression <- change_regression_nonNA(regression = regression, reg_nonNA = 20, reg_sig = reg_sig)
regression <- adjust_regression_by_nonNA(regression = regression, reg_nonNA = 20, reg_sig = reg_sig)

table(regression$Cancer)
```

```{r number-ks-pairs-detected}
regression %>%
  filter(SELF == "trans") %>%
  filter(enzyme_type == "kinase") %>%
  select(pair_pro) %>%
  unique() %>%
  nrow

regression %>%
  filter(SELF == "cis") %>%
  filter(enzyme_type == "kinase") %>%
  select(pair_pro) %>%
  unique() %>%
  nrow

regression %>%
  filter(SELF == "trans") %>%
  filter(enzyme_type == "phosphatase") %>%
  select(pair_pro) %>%
  unique() %>%
  nrow
```

```{r number-correlated-ks-pairs}
regression %>%
  filter(regulated == T) %>%
  filter(enzyme_type == "kinase") %>%
  select(pair) %>%
  unique() %>%
  nrow

regression %>%
  filter(regulated == T) %>%
  filter(enzyme_type == "kinase") %>%
  select(pair_pro) %>%
  unique() %>%
  nrow

regression %>%
  filter(regulated == T) %>%
  filter(enzyme_type == "phosphatase") %>%
  select(pair) %>%
  unique() %>%
  nrow

regression %>%
  filter(regulated == T) %>%
  filter(enzyme_type == "phosphatase") %>%
  select(pair_pro) %>%
  unique() %>%
  nrow

# 
# regression %>%
#   filter(GENE == "AKT1" & SUB_GENE == "GSK3B")
# 
# regression %>%
#   filter(GENE == "IKBKB" & SUB_GENE == "TP53")
# 
# regression %>%
#   filter(GENE == "RPTOR")
# 
# regression %>%
#   filter(GENE == "MTOR" & SUB_GENE == "EIF4EBP1")

```

```{r known-trans-specificity}
omnipath_tab %>%
  filter(pair_pro %in% regression$pair_pro) %>%
  filter(enzyme_type == "kinase") %>%
  select(GENE, SUB_GENE) %>%
  unique() %>%
  select(GENE) %>%
  table() %>%
  sort() %>%
  as.vector() %>%
  base::summary()

omnipath_tab %>%
  filter(pair_pro %in% regression$pair_pro) %>%
  filter(enzyme_type == "kinase") %>%
  filter(SUB_MOD_RSD != "NULL") %>%
  select(GENE, SUB_GENE, SUB_MOD_RSD) %>%
  unique() %>%
  select(GENE) %>%
  table() %>%
  sort() %>%
  as.vector() %>%
  base::summary()

omnipath_tab %>%
  filter(pair_pro %in% regression$pair_pro) %>%
  filter(enzyme_type == "phosphatase") %>%
  select(GENE, SUB_GENE) %>%
  unique() %>%
  select(GENE) %>%
  table() %>%
  sort() %>%
  as.vector() %>%
  base::summary()

omnipath_tab %>%
  filter(pair_pro %in% regression$pair_pro) %>%
  filter(enzyme_type == "phosphatase") %>%
  filter(SUB_MOD_RSD != "NULL") %>%
  select(GENE, SUB_GENE, SUB_MOD_RSD) %>%
  unique() %>%
  select(GENE) %>%
  table() %>%
  sort() %>%
  as.vector() %>%
  base::summary()

```

```{r regression-trans-kinase-specificity}
regression %>%
  filter(enzyme_type == "kinase") %>%
  filter(regulated == T) %>%
  select(GENE, SUB_GENE) %>%
  unique() %>%
  select(GENE) %>%
  table() %>%
  sort() %>%
  tail()

regression %>%
  filter(enzyme_type == "kinase") %>%
  filter(regulated == T) %>%
  select(GENE, SUB_GENE) %>%
  unique() %>%
  select(GENE) %>%
  table() %>%
  sort() %>%
  as.vector() %>%
  base::summary()

regression %>%
  filter(enzyme_type == "kinase") %>%
  filter(regulated == T) %>%
  select(GENE, SUB_GENE, SUB_MOD_RSD) %>%
  unique() %>%
  select(GENE) %>%
  table() %>%
  sort() %>%
  tail()


regression %>%
  filter(enzyme_type == "kinase") %>%
  filter(regulated == T) %>%
  select(GENE, SUB_GENE, SUB_MOD_RSD) %>%
  unique() %>%
  select(GENE) %>%
  table() %>%
  sort() %>%
  table()

regression %>%
  filter(enzyme_type == "kinase") %>%
  select(GENE) %>%
  unique() %>%
  nrow()

regression %>%
  filter(enzyme_type == "kinase") %>%
  filter(regulated == T) %>%
  select(GENE, SUB_GENE, SUB_MOD_RSD) %>%
  unique() %>%
  select(GENE) %>%
  table() %>%
  sort() %>%
  as.vector() %>%
  base::summary()

regression <- annotate_ks_source(regression = regression)
regression %>%
  filter(enzyme_type == "kinase") %>%
  filter(regulated == T) %>%
  select(GENE, SUB_GENE, SUB_MOD_RSD, is.direct) %>%
  unique() %>%
  select(GENE, is.direct) %>%
  table() %>%
  as.data.frame() %>%
  filter(is.direct == "TRUE") %>%
  select(Freq) %>%
  base::summary()

regression %>%
  filter(enzyme_type == "kinase") %>%
  filter(regulated == T) %>%
  filter(is.direct == F) %>%
  select(SUB_GENE, SUB_MOD_RSD) %>%
  unique() %>%
  nrow()

regression %>%
  filter(enzyme_type == "kinase") %>%
  filter(regulated == T) %>%
  filter(is.direct == F) %>%
  select(GENE) %>%
  unique() %>%
  nrow()

regression %>%
  filter(enzyme_type == "kinase") %>%
  filter(regulated == T) %>%
  filter(is.direct == F) %>%
  select(SUB_GENE) %>%
  unique() %>%
  nrow()

```

```{r coeffcient}
regression %>%
  filter(SELF == "trans") %>%
  filter(enzyme_type == "kinase") %>%
  filter(fdr_sig == T) %>%
  select(coef_sig) %>%
  table()
4109/(4109+1663)

regression %>%
  filter(SELF == "trans") %>%
  filter(enzyme_type == "phosphatase") %>%
  filter(fdr_sig == T) %>%
  select(coef_sig) %>%
  table()
208+342
208/550
```

```{r regression-trans-phosphatase-specificity}
regression %>%
  filter(enzyme_type == "phosphatase") %>%
  select(GENE) %>%
  unique() %>%
  nrow()

regression %>%
  filter(enzyme_type == "phosphatase") %>%
  filter(fdr_sig == T) %>%
  select(GENE) %>%
  unique() %>%
  nrow()

regression %>%
  filter(enzyme_type == "phosphatase") %>%
  filter(regulated == T) %>%
  select(GENE) %>%
  unique() %>%
  nrow()

regression %>%
  filter(enzyme_type == "phosphatase") %>%
  filter(regulated == T) %>%
  select(GENE, SUB_GENE) %>%
  unique() %>%
  select(GENE) %>%
  table() %>%
  sort() %>%
  tail()

regression %>%
  filter(enzyme_type == "phosphatase") %>%
  filter(regulated == T) %>%
  select(GENE, SUB_GENE) %>%
  unique() %>%
  select(GENE) %>%
  table() %>%
  sort() %>%
  as.vector() %>%
  base::summary()

regression %>%
  filter(enzyme_type == "phosphatase") %>%
  filter(regulated == T) %>%
  select(GENE, SUB_GENE, SUB_MOD_RSD) %>%
  unique() %>%
  select(GENE) %>%
  table() %>%
  sort() %>%
  tail()


regression %>%
  filter(enzyme_type == "phosphatase") %>%
  filter(regulated == T) %>%
  select(GENE, SUB_GENE, SUB_MOD_RSD) %>%
  unique() %>%
  select(GENE) %>%
  table() %>%
  sort() %>%
  table()



regression %>%
  filter(enzyme_type == "phosphatase") %>%
  filter(regulated == T) %>%
  select(GENE, SUB_GENE, SUB_MOD_RSD) %>%
  unique() %>%
  select(GENE) %>%
  table() %>%
  sort() %>%
  as.vector() %>%
  base::summary()

regression <- annotate_ks_source(regression = regression)
regression %>%
  filter(enzyme_type == "kinase") %>%
  filter(regulated == T) %>%
  select(GENE, SUB_GENE, SUB_MOD_RSD, is.direct) %>%
  unique() %>%
  select(GENE, is.direct) %>%
  table() %>%
  as.data.frame() %>%
  filter(is.direct == "TRUE") %>%
  select(Freq) %>%
  base::summary()

regression %>%
  filter(enzyme_type == "kinase") %>%
  filter(regulated == T) %>%
  filter(is.direct == F) %>%
  select(SUB_GENE, SUB_MOD_RSD) %>%
  unique() %>%
  nrow()

regression %>%
  filter(enzyme_type == "kinase") %>%
  filter(regulated == T) %>%
  filter(is.direct == F) %>%
  select(GENE) %>%
  unique() %>%
  nrow()

regression %>%
  filter(enzyme_type == "kinase") %>%
  filter(regulated == T) %>%
  filter(is.direct == F) %>%
  select(SUB_GENE) %>%
  unique() %>%
  nrow()

```

